### PR TITLE
fix(elements|ino-datepicker): use date format to improve validation

### LINKED ISSUE #225: InoDatepicker: "Cannot read property 'parseDate' of undefined"
### Describe the bug
InoDatepicker is set to invalid although the value has the proper format. 

### To Reproduce
Difficult to reproduce. Used `InoDatepicker` with React. The Error occured irregular on rendering the `InoDatepicker` within a Modal.

### Expected behavior
The invalid state should only be set if format is not correct.

### Your Environment
 

| Software | Version |
| -------- | ------- |
| @inovex.de/elements | v2.2.0
| Browser | Chrome
| Operating System | MacOS

### Possible Solution
It seems the flatpicker instance isnt't instantiated at the time of validating the value.

### PR DESCRIPTION
**Pull request by Sl1nd**
Closes #225 

- A debounce was not possible, because of the multiple possibilities to enter values (e.g. copy/paste, flatpicker)
- It also turned out that validating on blur leads to a worse user experience
- Only validate if flatpicker is set
- Also ino-range validation is fixed

### CODE REVIEW

File: packages/elements/src/components/ino-datepicker/ino-datepicker.tsx [hunk 1]
```diff
@@ -336,17 +341,30 @@ export class Datepicker implements ComponentInterface {
...
+    };
+  }
+
+  private validateInput(value: string): boolean {
+    let formattedDate: string;
+    let parsedDate: Date; 
+    parsedDate = this.flatpickr.parseDate(value);
+    formattedDate = this.flatpickr.formatDate(parsedDate, this.flatpickr.config.dateFormat);
     
+    return formattedDate !== value ?  false : true;
```
Comment (janivo) [inline packages/elements/src/components/ino-datepicker/ino-datepicker.tsx:367]: This can be simplified to `return formattedDate === value`, no?

File: packages/elements/src/components/ino-datepicker/ino-datepicker.tsx [hunk 2]
```diff
@@ -336,17 +341,30 @@ export class Datepicker implements ComponentInterface {
...
     }
+
+    if(!value && !this.required) {
+      this.isValid = true; 
+      return;
+    };
+  }
+
+  private validateInput(value: string): boolean {
+    let formattedDate: string;
```
Comment (janivo) [inline packages/elements/src/components/ino-datepicker/ino-datepicker.tsx:362]: We should use `const` if we do not have to use `let`

File: packages/elements/src/components/ino-datepicker/ino-datepicker.tsx [hunk 3]
```diff
@@ -336,17 +341,30 @@ export class Datepicker implements ComponentInterface {
   });
 
   private setValidState(value: string): void {
-    let formattedDate: string;
-    let parsedDate: Date;
+    if(this.inoRange) {
+      let arr = value.match(/(\d[^a-z]+)/g).map(match => this.validateInput(match.trim()));
```
Comment (janivo) [inline packages/elements/src/components/ino-datepicker/ino-datepicker.tsx:345]: We should use `const` if we do not have to use `let`

Comment (janivo) [inline packages/elements/src/components/ino-datepicker/ino-datepicker.tsx:345]: Could you extract that regex as a static member and give it a name? This way, it is more clear what the regex is supposed to test.

Comment (janivo) [inline packages/elements/src/components/ino-datepicker/ino-datepicker.tsx:345]: The name `arr` is kinda generic. Could you name it more spelling?

File: packages/elements/src/components/ino-datepicker/ino-datepicker.tsx [hunk 4]
```diff
@@ -58,9 +58,14 @@ export class Datepicker implements ComponentInterface {
 
   @Watch('value')
   valueChanged(value: string) {
-    this.setValidState(value);
-    if (this.flatpickr) {
-      this.flatpickr.setDate(value, false, this.inoDateFormat);
+    try {
+      if (this.flatpickr) {
+        this.setValidState(value);
+        this.flatpickr.setDate(value, false, this.inoDateFormat)
```
Comment (janivo) [inline packages/elements/src/components/ino-datepicker/ino-datepicker.tsx:64]: With this logic, the flatpickr will always set the date, even if it is invalid. Is this intended?

File: packages/elements/src/components/ino-datepicker/ino-datepicker.e2e.ts [hunk 5]
```diff
@@ -152,19 +153,22 @@ describe('InoDatepicker', () => {
       expect(datepicker).toHaveAttribute('ino-show-label-hint');
     });
 
-    it('should set invalid state for required inputs', async () => {
-      const page = await setupPageWithContent(INO_DATEPICKER);
+    it.only('should set invalid state for required inputs', async () => {
```
Comment (janivo) [inline packages/elements/src/components/ino-datepicker/ino-datepicker.e2e.ts:156]: Why the `only`?

**Review by janivo — CHANGES_REQUESTED** [review]

**Review by janivo — APPROVED** [review]
