### PR TITLE
fix(elements|ino-datepicker): only validate if value is set

### LINKED ISSUE #356: ino-datepicker: min/max dates set validation state if no value is set
### Describe the bug

Changes to minimum/maximum Date trigger the validation logic even if no value is set.

### To Reproduce

1. Go to https://elements.inovex.de/dist/latest/storybook/?path=/story/input-ino-datepicker--default-usage
2. Delete `value` & `ino-default-date` in `Date Config`
3. Change minimum Date in html via browser developer tools
4. See invalid state 

grafik

Expected behavior:
Only validate if Value is set

### PR DESCRIPTION
**Pull request by Sl1nd**
Closes #356 

## Proposed Changes

- Trigger validation logic only if value is truthy

### CODE REVIEW

File: packages/elements/src/components/ino-datepicker/validation.ts [hunk 1]
```diff
@@ -3,58 +3,191 @@ import flatpickr from 'flatpickr';
...
+    this.minDate = minDate;
+    this.maxDate = maxDate;
+  }
+
+  /**
+   * Validates the date in terms of format, require-state, disabled-state minimum date and maximum date.
+   * @param value The value to be validated
+   * @return true if the date is valid, false if the date is invalid
+   */
+  public validate = (value?: string): boolean => {
```
Comment (Sl1nd) [inline packages/elements/src/components/ino-datepicker/validation.ts:44]: Could we use isValid? IMO this would be more explicit considering the return values

File: packages/elements/src/components/ino-datepicker/ino-datepicker.tsx [hunk 2]
```diff
@@ -180,6 +159,7 @@ export class Datepicker implements ComponentInterface {
 
   @Watch('inoDateFormat')
   inoDateFormatChanged(dateFormat: string) {
+    this.validator.dateFormat = dateFormat;
```
Comment (Sl1nd) [inline packages/elements/src/components/ino-datepicker/ino-datepicker.tsx:162]: Should we also validate if dateformat changes? Maybe there is a valid usecase for dynamic format changes

File: packages/elements/src/components/ino-datepicker/validation.ts [hunk 3]
```diff
@@ -3,58 +3,191 @@ import flatpickr from 'flatpickr';
...
+  maxDate?: string;
 };
 
-export const validateMax = (
-  value: string,
-  format: string,
-  maxDateStr?: string
-): boolean => {
-  if (!maxDateStr) {
+export class DateValidator {
```
Comment (Sl1nd) [inline packages/elements/src/components/ino-datepicker/validation.ts:15]: Maybe Validator as class name is more universal. `Date` only relates to the type Dates. e.g. datetime, month as well as time are not covered

File: packages/elements/src/components/ino-datepicker/validation.ts [hunk 4]
```diff
@@ -3,58 +3,191 @@ import flatpickr from 'flatpickr';
...
+  public validate = (value?: string): boolean => {
+    if (this._isDisabled) {
+      return true;
+    }
+
+    if (!value && this._isRequired) {
+      return false;
+    }
+
+    if (!this.validateFormat(value)) {
```
Comment (Sl1nd) [inline packages/elements/src/components/ino-datepicker/validation.ts:53]: validateFormat and validateMax/validateMin has to be performed in parallel. Otherwise values outter scope  would produce valid date input

Comment (Sl1nd) [reply packages/elements/src/components/ino-datepicker/validation.ts:53]: e.g.

if(!value) return this._isRequired;

if(value)   return  validateMin&& validateMax && validateFormat;

see former implementation

File: packages/elements/src/components/ino-datepicker/validation.ts (hunk 1 above)
Comment (janivo) [reply packages/elements/src/components/ino-datepicker/validation.ts:44]: IMHO `isValid` would describe a variable rather than a function that calculates a validity status

File: packages/elements/src/components/ino-datepicker/validation.ts (hunk 4 above)
Comment (janivo) [reply packages/elements/src/components/ino-datepicker/validation.ts:53]: Do you have a concrete example where the current implementation would fail?
I could write it the way you described but I think this way the readability is better.

Comment (Sl1nd) [reply packages/elements/src/components/ino-datepicker/validation.ts]: Sorry my bad. I realized that the logic work as expected. The Issue that occured is due to parsing date in min and max setter. If the `minDate` is initialized asynchronous in any framework the value may be initially 'undefined' and the datepicker errors out. Maybe we should adjust the setter logic to only parse Values if value is not undefined

File: packages/elements/src/components/ino-datepicker/validator.ts [hunk 5]
```diff
@@ -0,0 +1,193 @@
...
+  }
+
+  set minDate(value: string | undefined) {
+    if (!value) {
+      this._minDate = undefined;
+      return;
+    }
+
+    try {
+      this._minDate = this.parseDate(value);
```
Comment (Sl1nd) [inline packages/elements/src/components/ino-datepicker/validator.ts:159]: The issue described below produces unnecessary console errors if `minDates` are initialized asynchronously. Maybe the `minDate`as well as `maxDate` only be parsed if it is not falsy (null|undefined|'"') otherwise it is set to undefined

**Comment by Sl1nd** [comment]
Currently the min/max changes are already validated if no value is present (storybook: value: null, default-date: null & required true -> change min date in Dev-Tools DOM).

**Comment by janivo** [comment]
> Currently the min/max changes are already validated if no value is present (storybook: value: null, default-date: null & required true -> change min date in Dev-Tools DOM).

That's expected because in that case, `null` is just handled as a string. If you want to provide an empty value to the `ino-datepicker` you should use `''` instead of `null` like this:
```jsx
<InoDatepicker ... value={this.myDate || ''} />
```

**Comment by Sl1nd** [comment]
> > Currently the min/max changes are already validated if no value is present (storybook: value: null, default-date: null & required true -> change min date in Dev-Tools DOM).
> 
> That's expected because in that case, `null` is just handled as a string. If you want to provide an empty value to the `ino-datepicker` you should use `''` instead of `null` like this:
> 
> ```js
> <InoDatepicker ... value={this.myDate || ''} />
> ```
This is not an issue of handling the Datepicker. In Storybook you may observe this behavior if you adjust the Date Config  Knob (Delete initial `value`, `ino-default-date` as well as setting required in Standard Knob

**Comment by Sl1nd** [comment]
Additionally i observe some error logs in React context using the datepicker in form on initalization:
grafik

grafik
grafik
grafik
grafik

**Comment by janivo** [comment]
> Additionally i observe some error logs in React context using the datepicker in form on initalization:
> grafik
> 
> grafik
> grafik
> grafik
> grafik

I see. These errors might be related to the initialization of the validator which happens after the component rendered in the DOM (concrete in `componentDidLoad`). I moved the initialization of the validator to the `componentWillLoad` lifecycle. Can you check again @Sl1nd?

**Comment by Sl1nd** [comment]
> > Additionally i observe some error logs in React context using the datepicker in form on initalization:
> > grafik
> > grafik
> > grafik
> > grafik
> > grafik
> 
> I see. These errors might be related to the initialization of the validator which happens after the component rendered in the DOM (concrete in `componentDidLoad`). I moved the initialization of the validator to the `componentWillLoad` lifecycle. Can you check again @Sl1nd?

Still present. I found a solution as i realized that the errors occure in all Watchers on setting the state for the validator. So checking if validator is present before setting state did fix the errors: e.g.

**Comment by Sl1nd** [comment]
> > > Currently the min/max changes are already validated if no value is present (storybook: value: null, default-date: null & required true -> change min date in Dev-Tools DOM).
> > 
> > 
> > That's expected because in that case, `null` is just handled as a string. If you want to provide an empty value to the `ino-datepicker` you should use `''` instead of `null` like this:
> > ```js
> > <InoDatepicker ... value={this.myDate || ''} />
> > ```
> 
> I think this is not an issue of handling the Datepicker. In Storybook you may observe this behavior if you adjust the `Date Config` Knob (Delete initial `value`, `ino-default-date` as well as setting` required` in `Standard` Knob
> Refer to issue description #356

Still the minimum and maximum validation is triggered if no value is set. We need to adjust the  min/max validation methods
e.g.:

```
private validateMinSingle = (value: string): boolean => {
    if(!value) return true;
    const parsedDate: Date = this.parseDate(value);
    return (
      isEqual(parsedDate, this._minDate) || isAfter(parsedDate, this._minDate)
    );
  };```

**Comment by Sl1nd** [comment]
@janivo  Works as expected. From my perspective this PR may be merged.

**Review by janivo — APPROVED** [review]
